### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by MuhammadAhmed8** [RitvijSrivastava/mark#1]
Hi, could you please tell me how to signup a user? I can't find a screen to register myself, or if there is a default user please list down. Thank you.

**Comment by ritvijsrivastava** [comment]
For Signing up, you need to Login as an admin, then add a user from there. I did not make a Sign Up page for the admin. (I don't know why? Probably was thinking about making another app just to handle admin side.)

I vaguely remember the test credentials. Try:

User Side:
email: test@test.com
password: test1234

Admin Side:
email: admin@admin.com
password: adminpass

Admin and User side have the same Login Screen and only differentiated by their email (Admin is hard-coded for now)

**Comment by ritvijsrivastava** [comment]
Let me know if these credentials work or not.

**Comment by kemi-mabel** [comment]
Hey, I have been able to log in as an admin, how do i add a user from there?

**Comment by kemi-mabel** [comment]
Hey, I have been able to log in as an admin, how do i add a user from there?

**Comment by kemi-mabel** [comment]
Hey, I have been able to log in as an admin, I'm trying to add a new user but it gets stuck at uploading

**Comment by ritvijsrivastava** [comment]
I just ran the app and turns out there is a problem with resetting the form after form submission. "The method 'reset' was called on null". Error is in _resetForm()_ in _employee_form.dart_

I did not delve deeper on why this error is popping up now, but you can safely navigate back and completely ignore the uploading screen (just wait for maybe 1-2s), since the user would certainly be created.

**Comment by kemi-mabel** [comment]
I just tried it now, i waited for about a minute. The user was not created.

**Comment by ritvijsrivastava** [comment]
Maybe try running the app via `flutter run -v` and see what the console is printing. Maybe it is throwing a different error ?
